name: Portfolio Report

# Schedule the workflow to run daily at 5 PM ET
on:
  schedule:
    - cron: '6 17 * * *'  # every day at 5 PM ET standard time (UTC-5)
  workflow_dispatch:   # also allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      env:
        PORTFOLIO_B64: ${{ secrets.PORTFOLIO_B64 }}
        SENDEREMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python main.py
